# 开发环境
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://docker:3306/shw${datasource_url_end_str}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    show-sql: false
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  boot:
    admin:
      client:
        url: ${ADMIN_SERVER_URL}
        username: ${ADMIN_SERVER_USERNAME}
        password: ${ADMIN_SERVER_PASSWORD}
logging:
  level: warn
  level.top: warn
cas:
  debug: true
  login-success-url: http://localhost:8090
  local-server-url: http://localhost:8080
  exclude:
    - '/config'
    - '/student/down'
    - '/teacher/down'